import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("train.csv")
print("First 5 Rows:\n")
print(df.head())
print("\nDataset Shape:")
print(df.shape)
print("\nDataset Info:")
print(df.info())
print("\nMissing Values:")
print(df.isnull().sum())

df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df.drop("Cabin", axis=1, inplace=True)
print("\nMissing Values After Cleaning:")
print(df.isnull().sum())
print("\nStatistical Summary:")
print(df.describe())
sns.set_style("whitegrid")
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="Survived")
plt.title("Survival Count")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(7,5))
sns.countplot(data=df, x="Sex", hue="Survived")
plt.title("Gender vs Survival")
plt.show()

plt.figure(figsize=(7,5))
sns.countplot(data=df, x="Pclass", hue="Survived")
plt.title("Passenger Class vs Survival")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df["Age"], bins=20, kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df["Fare"], bins=20, kde=True)
plt.title("Fare Distribution")
plt.xlabel("Fare")
plt.ylabel("Count")
plt.show()

print("\n========== INSIGHTS ==========")
print("1. Female passengers had a higher survival rate.")
print("2. First-class passengers survived more than second and third class.")
print("3. Most passengers were between 20 and 35 years old.")
print("4. Most passengers paid lower ticket fares.")
print("5. Age missing values were filled with the median.")
print("6. Cabin column was dropped because it had many missing values.")
print("7. Fare and passenger class have a relationship with survival.")